project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pca.qmd
    - rda.qmd
    - "part*.qmd"
    - "anova*.qmd"
    - ttest.qmd
    - glm.qmd
    - linearmodels.qmd
    - nhst-slide.qmd
    - ttest-slides.qmd
    - anova-slides.qmd
    - sakuma-drops.qmd
    - piping.qmd
    - descriptive_statistics-slide.qmd
    - openwater_nep_method.qmd
    - standardize_figures.qmd
    - tic_memo.qmd
    - "fish-demo*.qmd"

website:
  title: "データ解析（研究室用）"
  site-url: https://gnishihara.github.io/kenkyushitsu-kaiseki/
  repo-url: https://github.com/gnishihara/kenkyushitsu-kaiseki/
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: その前に
        contents:
        - index.qmd
        - part00.qmd
        - piping.qmd
      - section: Rの基礎
        contents:
        - part01.qmd
        - part02.qmd
        - part03.qmd
        - part04.qmd
        - part05.qmd
      - section: 線形モデル
        contents:
        - linearmodels.qmd
        - ttest.qmd
        - anova.qmd
        - anova2.qmd
        - glm.qmd
      - section: Multivariate
        contents:
        - text: 主成分分析（PCA）
          href: pca.qmd
        - text: 冗長性分析（RDA）
          href: rda.qmd
      - section: 基礎統計学用
        contents:
        - descriptive_statistics-slide.qmd
        - sakuma-drops.qmd
        - text: 大数の法則と中心極限定理 
          href: nhst-slide.qmd
        - text: 2群の分析（t 検定）
          href: ttest-slides.qmd
        - text: 3群以上の分析（分散分析）
          href: anova-slides.qmd
        - text: 藻場にいた魚の解析
        　href: fish-demo01.qmd
      - section: 研究室用
        contents: 
        - openwater_nep_method.qmd
        - standardize_figures.qmd
        - tic_memo.qmd
format:
  html:
    theme: [ cosmo, custom.scss]
    css: styles.css
    toc: true
    html-math-method: katex
    code-block-bg: true
    code-block-border-left: "#31BAE9"
reference-location: margin
citation-location: margin
bibliography: references.bib

execute: 
  freeze: auto
  

