project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pca.qmd
    - rda.qmd
    - "part*.qmd"
    - "anova*.qmd"
    - ttest.qmd
    - glm.qmd
    - linearmodels.qmd
    - nhst-slide.qmd
    - ttest-slides.qmd
    - anova-slides.qmd
    - sakuma-drops.qmd

website:
  title: "データ解析（研究室用）"
  site-url: https://gnishihara.github.io/kenkyushitsu-kaiseki/
  repo-url: https://github.com/gnishihara/kenkyushitsu-kaiseki/
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Introduction
        contents:
        - index.qmd
      - section: Rの基礎
        contents:
        - part01.qmd
        - part02.qmd
        - part03.qmd
        - part04.qmd
        - part05.qmd
      - section: Linear models
        contents:
        - linearmodels.qmd
        - ttest.qmd
        - anova.qmd
        - anova2.qmd
        - glm.qmd
      - section: Multivariate
        contents:
        - pca.qmd
        - rda.qmd
      - section: 基礎統計学用スライド
        contents:
        - descriptive_statistics-slide.qmd
        - sakuma-drops.qmd
        - ttest-slides.qmd
        - nhst-slide.qmd
        - anova-slides.qmd

format:
  html:
    theme: [ cosmo, custom.scss]
    css: styles.css
    toc: true
    html-math-method: katex
    code-block-bg: true
    code-block-border-left: "#31BAE9"
reference-location: margin
citation-location: margin
bibliography: references.bib

execute: 
  freeze: auto
  

